language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

notifications:
  email: false
  irc: "irc.freenode.org#fluent-php"

install: travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text

matrix:
  include:
    - php: 7.0
      dist: precise
  allow_failures:
    - php: hhvm
